const standardObjectFilters = {
    'patternList': [
        new RegExp('^ExtlClntApp'),     // ExternalClientApplication and related objects
        new RegExp('^Flow'),            // Flow and related objects
        new RegExp('^Oath'),            // Auth and related objects
        new RegExp('^PermissionSet'),   // Permission sets and related objects
        new RegExp('__mdt$'),           // Custom Metadata Types
        new RegExp('ChangeEvent$'),     // Change Data Capture event objects
        new RegExp('SharingRule$'),     // Sharing rules (access related entity)
        new RegExp('Config$'),          // Configuration objects
        new RegExp('Feed$'),            // Chatter feed objects
        new RegExp('Feedback$'),        // Feedback and related objects
        new RegExp('History$'),         // Field history tracking objects
        new RegExp('Instance$'),        // Objects related to specific instances of features
        new RegExp('Metric$'),          // Performance and other metrics objects
        new RegExp('Metrics$'),         // Performance and other metrics objects
        new RegExp('Settings$'),        // Various settings (mainly from Setup menu, which can't be migrated)
        new RegExp('View$'),            // List views and related objects
    ],
    'hardcodedList':[
        'ActorReactiveAskRespEvent',
        'AggregateResult',
        'AIApplication',
        'AIInsightAction',
        'AIInsightReason',
        'AIInsightValue',
        'AIPredictionEvent',
        'AIRecordInsight',
        'AnalyticsTaskStatusEvent',
        'ApexClass',
        'ApexComponent',
        'ApexEmailNotification',
        'ApexLog',
        'ApexPage',
        'ApexPageInfo',
        'ApexTestQueueItem',
        'ApexTestResultLimits',
        'ApexTestRunResult',
        'ApexTestSuite',
        'ApexTrigger',
        'ApexTypeImplementor',
        'ApiAnomalyEvent',
        'ApiAnomalyEventStore',
        'ApiEvent',
        'ApiEventStream',
        'ApprovalSubmission',
        'ApprovalSubmissionDetail',
        'ApprovalSubmissionShare',
        'ApprovalWorkItem',
        'AppTabMember', // requires filtering on durableId, entitydef or other.
        'AsgnRsrcApptSchdEvent',
        'AssetTokenEvent',
        'AsyncApexJob',
        'AsyncOperationEvent',
        'AsyncOperationLog',
        'AsyncOperationStatus',
        'AttachedContentDocument',
        'AuraDefinition',
        'AuraDefinitionBundle',
        'AuraDefinitionBundleInfo',
        'AuraDefinitionInfo',
        'AuthConfigProviders',
        'AuthProvider',
        'AuthProvParamFwdAllowlist',
        'AuthSession',
        'BatchApexErrorEvent',
        'BulkApiResultEvent',
        'BulkApiResultEventStore',
        'ColorDefinition',
        'CombinedAttachment',
        'ConcurLongRunApexErrEvent',
        'ContentDocumentLink',
        'ContentFolderItem',
        'ContentFolderMember',
        'ConversationApiLog',
        'ConversationApiLogObjSum',
        'CorsWhitelistEntry',
        'CredentialStuffingEvent',
        'CronJobDetail',
        'CronTrigger',
        'CspTrustedSite',
        'CuratedExpJobEvent',
        'CuratedExpPlanEvent',
        'CustomHttpHeader',
        'CustomNotificationType',
        'CustomPermission',
        'CustomPermissionDependency',
        'DatacloudAddress',
        'DatacloudCompany',
        'DatacloudContact',
        'DatacloudDandBCompany',
        'DatacloudOwnedEntity',
        'DatacloudPurchaseUsage',
        'DataEncryptionKey',
        'DataMaskCustomValueLibrary',
        'DataMaskCustomValueLibraryShare',
        'DataObjectDataChgEvent',
        'DataStatistics',
        'DataType',
        'DeleteEvent',
        'Domain',
        'DomainSite',
        'EmailBounceEvent',
        'EmailStatus',
        'EntityDefinition',
        'EntityParticle',
        'EvfPipelineSubTaskDetails',
        'ExpressionFilter',
        'ExpressionFilterCriteria',
        'ExternalClientApplication',
        'ExternalDataSource',
        'ExternalDataSrcDescriptor',
        'ExternalDataUserAuth',
        'ExternalEncryptionRootKey',
        'ExternalEvent',
        'ExternalEventMapping',
        'ExternalEventMappingShare',
        'FeedAttachment',
        'FeedComment',
        'FeedItem',
        'FeedLike',
        'FeedPollChoice',
        'FeedPollVote',
        'FeedRevision',
        'FeedSignal',
        'FeedTrackedChange',
        'FieldDefinition',
        'FieldPermissions',
        'FieldSecurityClassification',
        'FileEvent',
        'FileEventStore',
        'FlexQueueItem',
        'FolderedContentDocument',
        'FOStatusChangedEvent',
        'FulfillOrdItemQtyChgEvent',
        'GuestUserAnomalyEvent',
        'IconDefinition',
        'IdeaComment',
        'IdentityProviderEventStore',
        'IdentityVerificationEvent',
        'LightningExperienceTheme',
        'LightningUriEvent',
        'LightningUriEventStream',
        'ListViewChart',
        'ListViewEvent',
        'ListViewEventStream',
        'LoginAnomalyEvent',
        'LoginAnomalyEventStore',
        'LoginAsEvent',
        'LoginAsEventStream',
        'LoginEvent',
        'LoginEventStream',
        'LoginGeo',
        'LoginIp',
        'LogoutEvent',
        'LogoutEventStream',
        'LookedUpFromActivity',
        'MessagingConfiguration',
        'MLEngagementEvent',
        'MLModel',
        'MLModelFactor',
        'MLModelFactorComponent',
        'MsgSessStatusChangedEvent',
        'MutingPermissionSet',
        'Name',
        'NoteAndAttachment',
        'ObjectPermissions',
        'OpenActivity',
        'OpportunityRelatedDeleteLog',
        'OrgLifecycleNotification',
        'OutgoingEmail',
        'OwnedContentDocument',
        'OwnerChangeOptionInfo',
        'PendingOrderSummary',
        'PendingOrdSumProcEvent',
        'PicklistValueInfo',
        'PlatformStatusAlertEvent',
        'ProcessException',
        'ProcessExceptionEvent',
        'ProcessExceptionShare',
        'ProcessFlowMigration',
        'Profile',
        'QuickTextShare',
        'QuickTextUsage',
        'RecentlyViewed',
        'RecordType',
        'RemoteKeyCalloutEvent',
        'Report',
        'ReportAnomalyEvent',
        'ReportAnomalyEventStore',
        'ReportEvent',
        'ReportEventStream',
        'RetentionStoreUsage',
        'RetentionStoreUsageShare',
        'SessionPermSetActivation',
        'SetupAuditTrail',
        'SetupEntityAccess',
        'TabDefinition',
        'Translation',
        'User',
        'UserAppInfo',
        'UserAppMenuCustomization',
        'UserAppMenuCustomizationShare',
        'UserAppMenuItem',
        'UserDefinedLabel',
        'UserDefinedLabelShare',
        'UserEmailPreferredPerson',
        'UserEmailPreferredPersonShare',
        'UserEntityAccess',
        'UserFieldAccess',
        'UserLicense',
        'UserListViewCriterion',
        'UserLocalWebServerIdentity',
        'UserLocalWebServerIdentityShare',
        'UserLogin',
        'UserPackageLicense',
        'UserPermissionAccess',
        'UserPreference',
        'UserPrioritizedRecord',
        'UserPrioritizedRecordShare',
        'UserProvAccount',
        'UserProvAccountStaging',
        'UserProvisioningLog',
        'UserProvisioningRequest',
        'UserProvisioningRequestShare',
        'UserProvMockTarget',
        'UserRecordAccess',
        'UserSetupEntityAccess',
        'UserShare',
        'UserSharedFeature',
    ]
}



export default {
    ...standardObjectFilters,
}
