const standardObjectFilters = {
    'patternList': [
        new RegExp('^ExtlClntApp'),
        new RegExp('^Flow'),
        new RegExp('^Oath'),
        new RegExp('^PermissionSet'),
        new RegExp('__mdt$'),
        new RegExp('ChangeEvent$'),
        new RegExp('Config$'),
        new RegExp('Feed$'),
        new RegExp('Feedback$'),
        new RegExp('History$'),
        new RegExp('Instance$'),
        new RegExp('Metric$'),
        new RegExp('Metrics$'),
        new RegExp('Settings$'),
        new RegExp('View$'),
    ],
    'hardcodedList':[
        'ActorReactiveAskRespEvent',
        'AggregateResult',
        'AIApplication',
        'AIInsightAction',
        'AIInsightReason',
        'AIInsightValue',
        'AIPredictionEvent',
        'AIRecordInsight',
        'AnalyticsTaskStatusEvent',
        'ApexClass',
        'ApexComponent',
        'ApexEmailNotification',
        'ApexLog',
        'ApexPage',
        'ApexPageInfo',
        'ApexTestQueueItem',
        'ApexTestResultLimits',
        'ApexTestRunResult',
        'ApexTestSuite',
        'ApexTrigger',
        'ApexTypeImplementor',
        'ApiAnomalyEvent',
        'ApiAnomalyEventStore',
        'ApiEvent',
        'ApiEventStream',
        'ApprovalSubmission',
        'ApprovalSubmissionDetail',
        'ApprovalSubmissionShare',
        'ApprovalWorkItem',
        'AppTabMember', // requires filtering on durableId, entitydef or other.
        'AsgnRsrcApptSchdEvent',
        'AssetTokenEvent',
        'AsyncApexJob',
        'AsyncOperationEvent',
        'AsyncOperationLog',
        'AsyncOperationStatus',
        'AuraDefinition',
        'AuraDefinitionBundle',
        'AuraDefinitionBundleInfo',
        'AuraDefinitionInfo',
        'AuthConfigProviders',
        'AuthProvider',
        'AuthProvParamFwdAllowlist',
        'AuthSession',
        'BatchApexErrorEvent',
        'BulkApiResultEvent',
        'BulkApiResultEventStore',
        'ConcurLongRunApexErrEvent',
        'ConversationApiLog',
        'ConversationApiLogObjSum',
        'CorsWhitelistEntry',
        'CredentialStuffingEvent',
        'CronJobDetail',
        'CronTrigger',
        'CspTrustedSite',
        'CuratedExpJobEvent',
        'CuratedExpPlanEvent',
        'CustomHttpHeader',
        'CustomNotificationType',
        'CustomPermission',
        'CustomPermissionDependency',
        'DatacloudAddress',
        'DatacloudCompany',
        'DatacloudContact',
        'DatacloudDandBCompany',
        'DatacloudOwnedEntity',
        'DatacloudPurchaseUsage',
        'DataEncryptionKey',
        'DataMaskCustomValueLibrary',
        'DataMaskCustomValueLibraryShare',
        'DataObjectDataChgEvent',
        'DataStatistics',
        'DataType',
        'DeleteEvent',
        'Domain',
        'DomainSite',
        'EntityDefinition',
        'EvfPipelineSubTaskDetails',
        'ExpressionFilter',
        'ExpressionFilterCriteria',
        'ExternalClientApplication',
        'ExternalDataSource',
        'ExternalDataSrcDescriptor',
        'ExternalDataUserAuth',
        'ExternalEncryptionRootKey',
        'ExternalEvent',
        'ExternalEventMapping',
        'ExternalEventMappingShare',
        'FeedAttachment',
        'FeedComment',
        'FeedItem',
        'FeedLike',
        'FeedPollChoice',
        'FeedPollVote',
        'FeedRevision',
        'FeedSignal',
        'FeedTrackedChange',
        'FieldDefinition',
        'FieldPermissions',
        'FieldSecurityClassification',
        'FileEvent',
        'FileEventStore',
        'FOStatusChangedEvent',
        'FulfillOrdItemQtyChgEvent',
        'GuestUserAnomalyEvent',
        'IdentityProviderEventStore',
        'IdentityVerificationEvent',
        'LightningExperienceTheme',
        'LightningUriEvent',
        'LightningUriEventStream',
        'ListViewChart',
        'ListViewEvent',
        'ListViewEventStream',
        'LoginAnomalyEvent',
        'LoginAnomalyEventStore',
        'LoginAsEvent',
        'LoginAsEventStream',
        'LoginEvent',
        'LoginEventStream',
        'LoginGeo',
        'LoginIp',
        'LogoutEvent',
        'LogoutEventStream',
        'LookedUpFromActivity',
        'MessagingConfiguration',
        'MLEngagementEvent',
        'MLModel',
        'MLModelFactor',
        'MLModelFactorComponent',
        'MsgSessStatusChangedEvent',
        'MutingPermissionSet',
        'ObjectPermissions',
        'OpportunityRelatedDeleteLog',
        'PendingOrdSumProcEvent',
        'PicklistValueInfo',
        'PlatformStatusAlertEvent',
        'ProcessException',
        'ProcessExceptionEvent',
        'ProcessExceptionShare',
        'ProcessFlowMigration',
        'Profile',
        'QuickTextShare',
        'QuickTextUsage',
        'RecentlyViewed',
        'RecordType',
        'RemoteKeyCalloutEvent',
        'Report',
        'ReportAnomalyEvent',
        'ReportAnomalyEventStore',
        'ReportEvent',
        'ReportEventStream',
        'RetentionStoreUsage',
        'RetentionStoreUsageShare',
        'SessionPermSetActivation',
        'SetupAuditTrail',
        'SetupEntityAccess',
        'TabDefinition',
        'Translation',
        'User',
        'UserAppInfo',
        'UserAppMenuCustomization',
        'UserAppMenuCustomizationShare',
        'UserAppMenuItem',
        'UserDefinedLabel',
        'UserDefinedLabelShare',
        'UserEmailPreferredPerson',
        'UserEmailPreferredPersonShare',
        'UserEntityAccess',
        'UserFieldAccess',
        'UserLicense',
        'UserListViewCriterion',
        'UserLocalWebServerIdentity',
        'UserLocalWebServerIdentityShare',
        'UserLogin',
        'UserPackageLicense',
        'UserPermissionAccess',
        'UserPreference',
        'UserPrioritizedRecord',
        'UserPrioritizedRecordShare',
        'UserProvAccount',
        'UserProvAccountStaging',
        'UserProvisioningLog',
        'UserProvisioningRequest',
        'UserProvisioningRequestShare',
        'UserProvMockTarget',
        'UserRecordAccess',
        'UserSetupEntityAccess',
        'UserShare',
        'UserSharedFeature',
    ]
}



module.exports = {
    ...standardObjectFilters,
}
